const bcrypt = require('bcrypt');
const ObjectId = require('mongodb').ObjectID;

module.exports = [
  {
    _id: ObjectId('62ea6c42ef48c303cc904ce1'),
    fullName: 'Tonton',
    firstName: 'Tonton',
    lastName: 'Tonton',
    email: 'admin@sample.com',
    phoneNumber: '+250788558899',
    password: bcrypt.hashSync('secret', Number(10)),
    role: 'Admin',
    companyName: 'Timecapsule 3D',
    companyUrl: 'http://timecapsule.com',
    address: 'Kigali, RWanda',
    city: 'Kigali',
    country: 'Rwanda',
    currencyCode: 'CAD',
  },
  {
    _id: ObjectId('62ea6c42ef48c303cc904ce2'),
    fullName: 'Maombi',
    firstName: 'Maombi',
    lastName: 'Maombi',
    email: 'maombi@test.com',
    phoneNumber: '+250788558899',
    password: bcrypt.hashSync('secret', Number(10)),
    role: 'Client',
    companyName: 'Timecapsule 3D',
    companyUrl: 'http://timecapsule.com',
    address: 'Kigali, RWanda',
    city: 'Kigali',
    country: 'Rwanda',
    currencyCode: 'USD',
  },
  {
    _id: ObjectId('62ea6c42ef48c303cc904ce3'),
    fullName: 'eric',
    firstName: 'eric',
    lastName: ' niyonkuru',
    email: 'ericniyonkuru@gmail.com',
    phoneNumber: '+250787486966',
    password: bcrypt.hashSync('secret', Number(10)),
    role: 'Client',
    companyName: 'Timecapsule 3D',
    companyUrl: 'http://timecapsule.com',
    address: 'Kigali, RWanda',
    city: 'Kigali',
    country: 'Rwanda',
  },
  {
    _id: ObjectId('62ea6c42ef48c303cc904ce4'),
    fullName: 'Gatete',
    firstName: 'Gatete',
    lastName: 'Gatete',
    email: 'gatete@test.com',
    phoneNumber: '+250788558899',
    password: bcrypt.hashSync('secret', Number(10)),
    role: 'Manager',
    companyName: 'Timecapsule 3D',
    companyUrl: 'http://timecapsule.com',
    address: 'Kigali, RWanda',
    city: 'Kigali',
    country: 'Rwanda',
  },
  {
    _id: ObjectId('62ea6c42ef48c303cc904ce5'),
    fullName: 'Irenee',
    firstName: 'Irenee',
    lastName: 'Iradukunda',
    email: 'iradukundairenee9@gmail.com',
    phoneNumber: '+250787486966',
    password: bcrypt.hashSync('secret', Number(10)),
    role: 'Manager',
    companyName: 'Timecapsule 3D',
    companyUrl: 'http://timecapsule.com',
    address: 'Kigali, RWanda',
    city: 'Kigali',
    country: 'Rwanda',
  },
  {
    _id: ObjectId('62ea6c42ef48c303cc904ce6'),
    fullName: 'Lauren Mitchwel',
    firstName: 'Lauren',
    lastName: 'Mitchwel',
    email: 'lauren@abc.com',
    phoneNumber: '+250788558899',
    password: bcrypt.hashSync('secret', Number(10)),
    role: 'Manager',
    companyName: 'Timecapsule 3D',
    companyUrl: 'http://timecapsule.com',
    address: 'Kigali, RWanda',
    city: 'Kigali',
    country: 'Rwanda',
  },
  {
    _id: ObjectId('62ea6c42ef48c303cc904ce7'),
    fullName: 'Lauren Mitchwel',
    firstName: 'Lauren',
    lastName: 'Mitchwel',
    email: 'Mitchwel@test.com',
    phoneNumber: '+250788558899',
    password: bcrypt.hashSync('secret', Number(10)),
    role: 'Manager',
    companyName: 'Timecapsule 3D',
    companyUrl: 'http://timecapsule.com',
    address: 'Kigali, RWanda',
    city: 'Kigali',
    country: 'Rwanda',
  },
];
